# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:
  # orderers
  node0:
    container_name: node0
    image: bftsmart/fabric-orderingnode:amd64-1.3.0
    environment:
      - NODE_CONFIG_DIR=/bft-config/config
    volumes:
      - /home/anonymous/code/fabric-orderingservice/hlf_config/scripts/orderer0_material/:/bft-config/ 
    command: "0"
    networks:
      - byfn
  node1:
    container_name: node1
    image: bftsmart/fabric-orderingnode:amd64-1.3.0
    environment:
      - NODE_CONFIG_DIR=/bft-config/config
    volumes:
      - /home/anonymous/code/fabric-orderingservice/hlf_config/scripts/orderer1_material/:/bft-config/ 
    command: "1"
    networks:
      - byfn
  node2:
    container_name: node2
    image: bftsmart/fabric-orderingnode:amd64-1.3.0
    environment:
      - NODE_CONFIG_DIR=/bft-config/config
    volumes:
      - /home/anonymous/code/fabric-orderingservice/hlf_config/scripts/orderer2_material/:/bft-config/ 
    command: "2"
    networks:
      - byfn
  node3:
    container_name: node3
    image: bftsmart/fabric-orderingnode:amd64-1.3.0
    environment:
      - NODE_CONFIG_DIR=/bft-config/config
    volumes:
      - /home/anonymous/code/fabric-orderingservice/hlf_config/scripts/orderer3_material/:/bft-config/ 
    command: "3"
    networks:
      - byfn

  # frontends
  frontend1000:
    container_name: frontend1000
    image:  bftsmart/fabric-frontend:amd64-1.3.0
    environment:
      - FRONTEND_CONFIG_DIR=/bft-config/config/ 
      - FABRIC_CFG_PATH=/bft-config/fabric/ 
      #- ORDERER_GENERAL_LOGLEVEL=DEBUG
    volumes:
      - /home/anonymous/code/fabric-orderingservice/hlf_config/scripts/frontend1000_material:/bft-config/ 
    command: "1000"
    networks:
      - byfn
    depends_on:
      - node0
      - node1
      - node2
      - node3
    

  frontend2000:
    container_name: frontend2000
    image:  bftsmart/fabric-frontend:amd64-1.3.0
    environment:
      - FRONTEND_CONFIG_DIR=/bft-config/config/ 
      - FABRIC_CFG_PATH=/bft-config/fabric/ 
      - ORDERER_GENERAL_LOGLEVEL=INFO
    volumes:
      - /home/anonymous/code/fabric-orderingservice/hlf_config/scripts/frontend2000_material:/bft-config/ 
    command: "2000"
    networks:
      - byfn
    depends_on:
      - node0
      - node1
      - node2
      - node3

  #peers
  peer0:
    container_name: peer0
    #image: bftsmart/fabric-peer:amd64-1.3.0
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=0.peer.ibm.bft
      #- CORE_VM_ENDPOINT=http://172.17.0.1:2377
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_CFG_PATH=/bft-config/fabric/
    volumes:
      - /home/anonymous/code/fabric-orderingservice/hlf_config/scripts/peer0_material:/bft-config/
      - /var/run/:/host/var/run/  
    #command: peer node start
    networks:
      - byfn
    depends_on:
      - frontend1000
      - frontend2000
  peer1:
    container_name: peer1
    #image: bftsmart/fabric-peer:amd64-1.3.0
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=1.peer.ibm.bft
      #- CORE_VM_ENDPOINT=http://172.17.0.1:2377
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_CFG_PATH=/bft-config/fabric/
    volumes:
      - /home/anonymous/code/fabric-orderingservice/hlf_config/scripts/peer1_material:/bft-config/
      - /var/run/:/host/var/run/  
    networks:
      - byfn
    depends_on:
      - frontend1000
      - frontend2000
  peer2:
    container_name: peer2
    #image: bftsmart/fabric-peer:amd64-1.3.0
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=2.peer.ibm.bft
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_CFG_PATH=/bft-config/fabric/
    volumes:
      - /home/anonymous/code/fabric-orderingservice/hlf_config/scripts/peer2_material:/bft-config/
      - /var/run/:/host/var/run/  
    networks:
      - byfn
    ports:
      - 9051:7051
      - 9053:7053
    depends_on:
      - frontend1000
      - frontend2000
  peer3:
    container_name: peer3
    #image: bftsmart/fabric-peer:amd64-1.3.0
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=3.peer.ibm.bft
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_CFG_PATH=/bft-config/fabric/
    volumes:
      - /home/anonymous/code/fabric-orderingservice/hlf_config/scripts/peer3_material:/bft-config/
      - /var/run/:/host/var/run/  
    networks:
      - byfn
    ports:
      - 10051:7051
      - 10053:7053
    depends_on:
      - frontend1000
      - frontend2000

  cli:
    container_name: cli
    #image: bftsmart/fabric-tools:amd64-1.3.0
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      # - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # - CORE_VM_ENDPOINT=http://172.17.0.1:2375
      # - CORE_LOGGING_LEVEL=DEBUG
      - FABRIC_CFG_PATH=/bft-config/fabric 
      # - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0:7051
      #- CORE_PEER_MSPCONFIGPATH=/bft-config/fabric/crypto-config/peerOrganizations/ibm.bft/users/Admin\@ibm.bft/msp/
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ibm.bft/users/Admin@ibm.bft/msp

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - /home/anonymous/code/fabric-orderingservice/hlf_config/scripts/cli0_material:/bft-config/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0
      - peer1
      - peer2
      - peer3
    networks:
      - byfn
